### PR TITLE
Add git help commands gifs

### PR DESCRIPTION
**Pull request by sakshivij**
ref #3

### CODE REVIEW

**Comment by sakshivij** [comment]
ref #3

**Comment by sakshivij** [comment]
Still need to add two more GIF, PR not ready for review yet.

**Comment by tapaswenipathak** [comment]
Instead of writing multiple comments, you can write in the PR description the ticket you are closing.

**Review by tapaswenipathak — COMMENTED** [review]
Can you remove gitgifs/static/gifs/git write-tree.gif? Let me know if you need any help w/ git.

**Review by tapaswenipathak — COMMENTED** [review]
This PR should be having

git help --all - Present
git help --[no-]verbose] - ?
git help --guide - Present
git help --info - ?
git help --man - Present
git help --web - ?

**Review by tapaswenipathak — COMMENTED** [review]
I see git init gifs as well.

**Review by tapaswenipathak — COMMENTED** [review]
You should work on the commits as well, let's discuss the work, completed git help commands, nice work!

**Review by tapaswenipathak — CHANGES_REQUESTED** [review]
Left few minor comments. Let's fix as per comments soon. Feel free chatting w/ me for anything.

**Comment by sakshivij** [comment]
Ack. I will commit them by today EOD along with 20 more tickets that I am working on.

**Comment by tapaswenipathak** [comment]
On Wed, May 29, 2019 at 7:43 AM SAKSHI VIJ <notifications@github.com> wrote:
>
> Ack. I will commit them by today EOD along with more tickets that I am working on.

Write Fix #ticket number in the description of the PR from now on. I did it for you.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Tapasweni

**Review by tapaswenipathak — COMMENTED** [review]
@sakshivij assign me pr after you are done.

**Comment by sakshivij** [comment]
@tapaswenipathak Facing some issues with rest 2 commands: 
~$ git help --web push
fatal: '/usr/share/doc/git/html': not a documentation directory.

~$ git help --no-verbose push
error: unknown option `no-verbose'
usage: git help [--all] [--guides] [--man | --web | --info] [<command>]

    -a, --all             print all available commands
    -g, --guides          print list of useful guides
    -m, --man             show man page
    -w, --web             show manual in web browser
    -i, --info            show info page

Any inputs would be really helpful.

**Comment by sakshivij** [comment]
> @sakshivij assign me pr after you are done.

Ack

**Comment by tapaswenipathak** [comment]
On Wed, May 29, 2019 at 11:00 PM SAKSHI VIJ <notifications@github.com> wrote:
>
> @tapaswenipathak Facing some issues with few commands:
> ~$ git help --web push
> fatal: '/usr/share/doc/git/html': a documentation directory.
>
> ~$ git help --no-verbose push
> error: unknown option `no-verbose'
> usage: git help [--all] [--guides] [--man | --web | --info] []
>
> -a, --all             print all available commands
> -g, --guides          print list of useful guides
> -m, --man             show man page
> -w, --web             show manual in web browser
> -i, --info            show info page
>
> Any inputs would be really helpful.

Let's get on a call https://calendly.com/tapaswenipathak.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Tapasweni

**Comment by sakshivij** [comment]
The issue for above both still not resolved. Any hints where I go wrong?

**Pull request merged**
