### PR TITLE
Git add GIF

### LINKED ISSUE #11: Add GIFs of git add command
- [x] `git add --verbose`
- [x] `git add --force`
- [x]  `git add --interactive`
- [x]  `git add --update`
- [ ]  `git add --chmod=(+|-)x`
- [ ]  `git add --ignore-errors`

### PR DESCRIPTION
**Pull request by sakshivij**
Fix #11

### CODE REVIEW

**Review by tapaswenipathak — COMMENTED** [review]
`git add --interactive`, should show the output when run a command.

Screen Shot 2019-06-04 at 10 30 47 AM

**Review by tapaswenipathak — COMMENTED** [review]
In `git add verbose` GIF, run `git add --verbose`, `git add` and then `git status`.

**Review by tapaswenipathak — COMMENTED** [review]
left few minor comments.

**Comment by sakshivij** [comment]
> `git add --interactive`, should show the output when run a command.
> 
> Screen Shot 2019-06-04 at 10 30 47 AM

What kind of output?

**Comment by sakshivij** [comment]
> In `git add verbose` GIF, run `git add --verbose`, `git add` and then `git status`.

Ack. Will make changes

**Pull request merged**
