### PR TITLE
Git shortlog

### LINKED ISSUE #20: Add GIFs of git shortlog command
- `git log --pretty=short`
- `git shortlog --numbered`
- `git shortlog --summary`
- `git shortlog --email`
- `git shortlog --committer`

### PR DESCRIPTION
**Pull request by sakshivij**
fix #20

### CODE REVIEW

**Review by tapaswenipathak — COMMENTED** [review]
in git-shortlog-summary command you should be adding summary in commit, than you get an output.

**Review by tapaswenipathak — COMMENTED** [review]
in git-log-pretty-short commit, you should have a long commit and short commit (description commit) than you will get a output

**Review by tapaswenipathak — COMMENTED** [review]
git-shortlog-numbered is for sorting the number of commits per author, you should commit from multiple author names/mail ids and than run the command

**Review by tapaswenipathak — COMMENTED** [review]
committer can be different than author, you should add different committer in a merge command and than run git-log-committer command.

**Review by tapaswenipathak — CHANGES_REQUESTED** [review]
Left few minor comments.

**Comment by sakshivij** [comment]
@tapaswenipathak  Changes committed

**Pull request merged**
