### PR TITLE
Adding git init GIF

### LINKED ISSUE #1: Add GIF of git init command
`git init --q`
`git init --template`
`git init --separate-git-dir<git dir>`
`git --shared[=(false|true|umask|group|all|world|everybody|0xxx)]`
`git init unmask`

### PR DESCRIPTION
**Pull request by sakshivij**
Fix #1

### CODE REVIEW

**Review by tapaswenipathak — COMMENTED** [review]
Few things, the GIF should be exactly how I [added](https://github.com/tapaswenipathak/GitGIFs/tree/master/gitgifs/static/gifs).

- White screen, black text
- The GIF implemented would be having only `$` prompt present.

Let's have a call https://calendly.com/tapaswenipathak, I will write few things on the tickets as well.

**Comment by sakshivij** [comment]
Okay. The inputs would be really helpful.

**Comment by sakshivij** [comment]
@tapaswenipathak made the necessary changes and added some GIF. Let me know if any changes need to be made.

**Comment by tapaswenipathak** [comment]
On Fri, 24 May 2019, 22:25 SAKSHI VIJ <notifications@github.com wrote:

> @tapaswenipathak <https://github.com/tapaswenipathak> made the necessary
> changes and added few GIFs. Let me know if any changes are needed.
>

Submit work per ticket.

**Comment by sakshivij** [comment]
ref #1

**Review by tapaswenipathak — COMMENTED** [review]
- When you are creating gifs, you should remove sakshi, should have username instead.
- Font should be https://github.com/tapaswenipathak/setitup/tree/master/font.
- Orange line on the right side should be removed

**Review by tapaswenipathak — COMMENTED** [review]
In `git init --q` you should generate error message, the command is for finding errors in `git init`.

**Review by tapaswenipathak — COMMENTED** [review]
In `git init --separate-git-dir`, you should `ls` the separate-git-dir created. This command is for having a git directory in place of `.git/`.

**Review by tapaswenipathak — COMMENTED** [review]
`git-init--shared-all` is for group of users. You should create multi user or show the `.git/config`.

**Review by tapaswenipathak — COMMENTED** [review]
`git init --template`?

**Review by tapaswenipathak — COMMENTED** [review]
`git-init--shared-false` should show multi user `git init` share errors.

**Review by tapaswenipathak — COMMENTED** [review]
While creating gifs think in terms of

- You are a user who is viewing gifs and learning git
- gifs should inform more, as less writing as can be
- No sakshivij credentials shown
- Font type and size clear and visible

Let me know if you have any questions. Nice work! after you get few git gifs in it will be quick.

**Comment by sakshivij** [comment]
I am working on the gif that might be reason some are missing. Will make changes according to the suggestion and submit. Thanks for the inputs!

**Comment by sakshivij** [comment]
>     * When you are creating gifs, you should remove sakshi, should have username instead.
how do i do this?

**Comment by sakshivij** [comment]
>     * Font should be https://github.com/tapaswenipathak/setitup/tree/master/font.
The file in this repository doesn't seem to work

**Comment by sakshivij** [comment]
@tapaswenipathak

**Review by tapaswenipathak — COMMENTED** [review]
Let's have a sync on git.

**Review by tapaswenipathak — COMMENTED** [review]
Did you forgot using sudo in git-init-q.gif ?

**Review by tapaswenipathak — COMMENTED** [review]
Please write what is git-init-q1.gif?

**Review by tapaswenipathak — COMMENTED** [review]
git-init-template.gif can be merged.

**Review by tapaswenipathak — COMMENTED** [review]
git-init-unmask.gif can be merged as well

**Review by tapaswenipathak — COMMENTED** [review]
git-shared-true.gif can be merged.

**Review by tapaswenipathak — COMMENTED** [review]
Fix the commits, let me know if you need any help.

**Review by tapaswenipathak — CHANGES_REQUESTED** [review]
Left few minor comments. Let's fix as per comments soon. Feel free chatting w/ me for anything.

**Comment by sakshivij** [comment]
Ack!

**Review by tapaswenipathak — COMMENTED** [review]
@sakshivij assign me pr after you are done.

**Comment by sakshivij** [comment]
@tapaswenipathak  can you look at git-init-q1.gif instead?

**Comment by sakshivij** [comment]
@tapaswenipathak  this pr can be reviewed. I would appreciate corrections.
Some points:
git-init-q(try) :   GIF will be edited. Follows instructions as suggested, but no error
git-init-separate-git-dir :  the image still contains home/sakshi/  as updating profile name doesn't affect the username path in UBUNTU. Any inputs that you can give for changing would be really helpful.

**Comment by tapaswenipathak** [comment]
On Fri, May 31, 2019 at 11:51 PM SAKSHI VIJ <notifications@github.com> wrote:
>
> @tapaswenipathak this pr can be reviewed. I would appreciate corrections.
> Some points:
> git-init-q : GIF will be edited. Follows instructions as suggested, but no error
> git-init-separate-git-dir : the image still contains home/sakshi/ as updating profile name doesn't affect the username path in UBUNTU. Any inputs that you can give for changing would be really helpful.

What?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Tapasweni

**Comment by sakshivij** [comment]
Communicated in slack.

**Pull request merged**
