### PR TITLE
Use `description` instead `description in README

### PR DESCRIPTION
**Pull request by Sparker0i**
Added tilde character in description word

### CODE REVIEW

**Review by tapaswenipathak — CHANGES_REQUESTED** [review]
Well ` is called backtick character. Please update the commit msg as per the heading of this pull request and description.

You can find the commands [here](https://git-scm.com/docs/git-commit).

**Comment by Sparker0i** [comment]
I've made the change you requested

**Comment by tapaswenipathak** [comment]
Are the commits squashed?

**Comment by tapaswenipathak** [comment]
Looks good, pl. squash the commits.

**Comment by tapaswenipathak** [comment]
closing as stale.

**Pull request closed without merging**
